eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 30 #心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60 #发呆时间，即服务续约到期时间（缺省为90s）
  client:
    serviceUrl:
      defaultZone: http://admin:bjs191@localhost:9002/eureka/ #去哪里注册，eureka服务地址
    registry-fetch-interval-seconds: 30
    enabled: true