server:
  max-threads: 800
spring:
  zipkin:
    base-url: http://localhost:9011
  sleuth:
    enabled: false
    sampler:
      percentage: 1 #采样率，值为[0,1]之间的任意实数，顾名思义，这里代表100%采集报告。
eureka:
  instance:
    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5 #心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10 #发呆时间，即服务续约到期时间（缺省为90s）
  client:
    serviceUrl:          
       defaultZone: http://admin:bjs191@localhost:9002/eureka/
    registry-fetch-interval-seconds: 5
    enabled: true
feign:
  hystrix: 
    enabled: false
hystrix:
  command:
   default:
    execution:
     isolation:
      thread:
       timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000